version: "2"
services:
  all:
    image: bash:latest
    command: /bin/true
    depends_on:
      - "otel-collector"
      - "otel-agent"
      - "users"
      - "web"
      - "web-load"

  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "55670:55679" # zpages extension

  otel-agent:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1777:1777"   # pprof extension
      - "13133"       # health_check
    depends_on:
      - otel-collector

  web:
    build:
      context: web/
    environment:
      FLASK_APP: /app/app.py
      OTEL_EXPORTER_OTLP_SPAN_INSECURE: "True"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production"
    command: opentelemetry-instrument -s web flask run --port 8082 --host 0.0.0.0
    stdin_open: true
    tty: true
    volumes:
      - ./web:/app/

  users:
    build:
      context: users/
    environment:
      FLASK_APP: /app/app.py
      OTEL_EXPORTER_OTLP_SPAN_INSECURE: "True"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production"
    command: opentelemetry-instrument -s users flask run --port 8082 --host 0.0.0.0
    stdin_open: true
    tty: true
    volumes:
      - ./users:/app/

  web-load:
    image: locustio/locust
    volumes:
      - ./load/:/mnt/locust
    command: -f /mnt/locust/web.py --headless --host http://web:8082

  curl:
    image: curlimages/curl


networks:
  default:
    external:
      name: gorbeia_default
